//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InDepthAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InDepthAnalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap existing {
            get {
                object obj = ResourceManager.GetObject("existing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Template&gt;
        ///  &lt;TemplateInfo&gt;
        ///    &lt;Name&gt;&lt;![CDATA[In-depth Analysis]]&gt;&lt;/Name&gt;
        ///    &lt;Title&gt;&lt;![CDATA[In-depth Analysis]]&gt;&lt;/Title&gt;
        ///    &lt;Button&gt;[baseCountry]&lt;/Button&gt;
        ///    &lt;Description&gt;&lt;/Description&gt;
        ///    &lt;GeneralDescription&gt;&lt;![CDATA[
        ///    &lt;p style=&apos;line-height:1.5;color:Tomato;font-size:20px&apos;&gt;&lt;b&gt;Common concepts&lt;/b&gt;&lt;/p&gt;
        ///    &lt;p style=&apos;line-height:1.5&apos;&gt;&lt;span style=&apos;color:Tomato;font-size:14px&apos;&gt;&lt;b&gt;Formulas&lt;/b&gt;&lt;/span&gt;&lt;br&gt;
        ///    allow for the following components:&lt;/p&gt;
        ///    &lt;ul style=&apos;line-height:1.5&apos;&gt;
        ///    &lt;li&gt;&lt;span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InDepthAnalysis {
            get {
                return ResourceManager.GetString("InDepthAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap missing {
            get {
                object obj = ResourceManager.GetObject("missing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
