using System.Linq;

namespace EM_Statistics
{
    internal static partial class PrettyInfoProvider
    {
        private static class PrettyInfoFileGenesis
        {
            internal static string GetPrettyRunLog(SystemInfo.FileGenesis fileGenesis)
            {
                return $"Software-Version: {fileGenesis.generalInfo.softwareVersion}<br>" +
                       $"Project: {fileGenesis.generalInfo.project}<br>" +
                       $"System: {fileGenesis.runInfo.systemName}<br>" +
                       $"Dataset: {fileGenesis.runInfo.databaseName}<br>" +
                       $"Extension-Switches: {string.Join(" ", from es in fileGenesis.runInfo.extensionSwitches select $"{es.Key}={es.Value}")}" +
                       (!fileGenesis.runInfo.addOnSystemNames.Any() ? string.Empty : $"<br>AddOn{(fileGenesis.runInfo.addOnSystemNames.Count > 1 ? "s" : string.Empty)}: {string.Join(" ", fileGenesis.runInfo.addOnSystemNames)}");
            }

            internal static string GetPrettyRunLogExtended(SystemInfo.FileGenesis fileGenesis)
            {
                return (fileGenesis.petInfo == null ? string.Empty : "Generated by PET<br>") +
                       $"Run-id: {fileGenesis.runInfo.runId}<br>" +
                       $"{GetPrettyRunLog(fileGenesis)}<br>" +
                       $"Run-duration: {fileGenesis.runInfo.duration.GetStartTime_s()} - {fileGenesis.runInfo.duration.GetEndTime_s()} ({fileGenesis.runInfo.duration.GetDuration()})<br>" +
                       $"Currency: {fileGenesis.runInfo.currency}<br>" +
                       $"Exchange-rate: {fileGenesis.runInfo.exchangeRate}" +
                       (!fileGenesis.runInfo.errorInfo.Any() ? string.Empty : $"<br>Run produced {fileGenesis.runInfo.errorInfo.Count} warning{(fileGenesis.runInfo.errorInfo.Count > 1 ? "s" : string.Empty)}");
            }

            internal static string GetPrettyErrLog(SystemInfo.FileGenesis fileGenesis)
            {
                return string.Join("<br>", from ei in fileGenesis.runInfo.errorInfo select ei.message);
            }
        }
    }
}
